s=input('enter a string.\n')
a=len(s)
print('DISPLAY...\n')
print('string:',s)
str_f=input('input finding string/character.\n')
print('string:',s)
print('length:',a)
f=s.find(str_f)
print('location:',f)
