s=input('enter a string.\n')
a=len(s)
print('DISPLAY...\n')
print('string:',s)
x=input('input replace string/character.\n')
y=input('input the removal number.\n')
s=s.replace('+','x')
print('string:',s)
print('length:',a)
print('replace:',f)
